on: 
  push:
    branches: [students]
jobs:
  update-students-repo:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get assignment name"
        shell: bash -l {0}
        run: |
          echo "ASSIGNMENT=$(echo $GITHUB_REPOSITORY | cut -d/ -f2 | cut -d- -f1)" >> $GITHUB_ENV;
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Update URLs"
        shell: bash -l {0}
        run: |
          find . -type f -not -path '*/\.*' -exec \
          sed -i "s|$ASSIGNMENT-solution|$ASSIGNMENT|g" {} +
      - name: "Update devcontainer path"
        shell: bash -l {0}
        run: |
          sed -i "s|assignment_name_placeholder|$ASSIGNMENT|g" .devcontainer/devcontainer.json
      - name: "Commit and push changes to assignment (without solution) repo"
        shell: bash -l {0}
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > $HOME/.ssh/deploy_key
          chmod 600 $HOME/.ssh/deploy_key
          ssh-keyscan -H $GITHUB_SERVER > $HOME/.ssh/known_hosts
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/deploy_key -o UserKnownHostsFile=$HOME/.ssh/known_hosts"
          git config user.name "GitHub Actions Bot";
          git config user.email "<>";
          git remote set-url origin git@github.com:PGE383-HPC/$ASSIGNMENT.git;
          git commit -am "Update README URLs";
          git branch -M master
          git push origin master -f
