on: 
  create:
    branches: [master]
jobs:
  update-badges:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get assignment name"
        shell: bash -l {0}
        run: |
          echo "ASSIGNMENT=$(echo $GITHUB_REPOSITORY | cut -d/ -f2 | cut -d- -f1)" >> $GITHUB_ENV;
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Update URLs in badges"
        shell: bash -l {0}
        run: |
          sed -i "s|PGE383-HPC/$ASSIGNMENT/actions|$GITHUB_REPOSITORY/actions|g" README.md
      - name: Autocommit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update badge URL paths"
